# Create new aspace instance for a new client
# This will launch into the private VPC 
# Needs to be run from the ingest front machine
#
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - fail: msg='Need to set tenant name by adding --extra-vars "tenant_name=<new tenant name>" to ansible-playbook call'
    when: tenant_name == None
  - name: create a new aspace instance in the private vpc
    local_action:
      module: ec2
      count: 1
      state: present
      region: "{{ region }}"
      key_name: "{{ key_name }}"
      image: "{{ image_hvm }}"
      instance_type: "{{ instance_type }}"
      instance_profile_name: s3-readonly
      group_id: [ "{{ sec_grp_ingest_private_id }}" ]
      wait: true
      wait_timeout: 500
      vpc_subnet_id: "{{ subnet_id_private }}"
      instance_tags:
          project: "{{ tag_project }}"
          Name: "aspace-{{tenant_name}}"
      volumes:
      - device_name: /dev/xvda
        device_type: gp2
        volume_size: 16
        delete_on_termination: no
    register: aspace_instance
  - name: save aspace instance information to hosts
    lineinfile:
        dest: ./hosts
        line: "{{ tenant_name }} ansible_ssh_host=aspace_instance.private_ip ansible_ssh_private_key_file=~/.ssh/cluster.pem"
        insertafter: "[aspace_instances]"
