# Update the connection for new DB
# call by --limit=<current version> --extra-vars="previous_version=<previous version>"
---
-   hosts: localhost
    tasks:
      - name: change connect to the new DB server
        lineinfile:
          dest: /etc/stunnel/stunnel.conf
          regexp: "^connect ="
          state: present
          line: "connect = {{ db_server }}:3306"
        become: yes
      - name: restart stunnel
        service:
          name: stunnel
          state: restarted
