---
# tasks file for setup_new_client_software
- include: generate_aspace_secrets.yml
- set_fact:
    url_jdbc_aspace: "{{ url_jdbc_base }}{{ client_name }}?user={{ client_name }}&password={{ client_db_password }}{{ url_jdbc_suffix }}"
- name: get archivesspace 1.3.0 zip file
  get_url: 
    url: https://github.com/archivesspace/archivesspace/releases/download/v1.3.0/archivesspace-v1.3.0.zip
    dest: ~/archivesspace-v1.3.0.zip
    sha256sum: cd2ff0b56a91b6daa3224ccf8704638baa23c71a831440a07bfb92c68bd02c92 
- name: config client db access
  template: src=templates/aspace/config.rb.j2 dest=~/archivesspace/clients/{{ client_name }}/archivesspace/config/config.rb
- name: setup client database
  shell: chdir={{ dir_aspace_root }}/archivesspace/clients/{{ client_name }}/archivesspace/ ./scripts/setup-database.sh
- include: aspace_save_client_info.yml
- name: create monit monitor for client
  become: yes
  template: src=templates/aspace/aspace.monitrc dest=/etc/monit.d/aspace.monitrc
- debug: msg="MYSQL PASSWORD FOR {{ client_name }} -- {{ client_db_password }}"
