---
# tasks file for setup_new_client_software
- include: generate_aspace_secrets.yml
- set_fact:
    url_jdbc_aspace: "{{ url_jdbc_base }}{{ client_name }}?user={{ client_name }}&password={{ client_db_password }}{{ url_jdbc_suffix }}"
- debug: var=url_jdbc_aspace
- name: get archivesspace {{ aspace_version }} zip file
  copy: 
    src: "archivesspace-{{ aspace_version }}.zip"
    dest: "~/archivesspace-{{ aspace_version }}.zip"
- name: unzip archivesspace into client user home dir
  unarchive:
    dest: "/home/{{ client_name }}/"
    src: "/home/{{ client_name }}/archivesspace-{{ aspace_version }}.zip"
    copy: no
- name: get and put mysql connector in place
  get_url:
    url: https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.36/mysql-connector-java-5.1.36.jar
    dest: "/home/{{ client_name }}/archivesspace/lib/"
    sha256sum: 7ba5290be5844b5bbdae3e4bee7e6a86b62b5feeacd224b60e66530df40a307a
    force: no
- name: config client db access
  template: src=config.rb.j2 dest=~/archivesspace/config/config.rb
- name: setup client database
  shell: chdir=~/archivesspace/ ./scripts/setup-database.sh
- include: aspace_save_client_info.yml
- debug: msg="MYSQL PASSWORD FOR {{ client_name }} -- {{ client_db_password }}"
